version: '3'

services:
  web:
    build: .
    container_name: good-night-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app      
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: good-night-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
